"""The worked examples, the resolution map, and the export guard.

An example that has drifted from the artifacts it cites is worse than no
example: it still looks like evidence. So the examples are regenerated by a
tool and this module fails if the committed files differ from what the tool
produces.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
SCHEMAS = REPO / "schemas"
CONTRACT = REPO / "docs" / "contract"
EXAMPLES = CONTRACT / "examples"
sys.path.insert(0, str(REPO / "fixtures" / "canary"))

from _engine.schema_check import validate  # noqa: E402

CONTRACT_SCHEMA_FILES = {
    "RunManifest.v2.schema.json", "EventLog.schema.json",
    "CanaryResult.schema.json", "ContHarnessInput.schema.json",
    "ContHarnessOutput.schema.json", "ContHarnessParameters.schema.json",
}

# Calendar 2.1, one entry per bullet sub-item. The list is the calendar's, not
# this repository's; it is restated here only so that a silent addition or
# deletion in the map fails a test.
EXPECTED_ITEM_REFS = [
    "2.1-1a", "2.1-1b", "2.1-1c", "2.1-1d",
    "2.1-2a", "2.1-2b", "2.1-2c", "2.1-2d", "2.1-2e",
    "2.1-3a", "2.1-3b", "2.1-3c", "2.1-3d",
    "2.1-4a",
    "2.1-5a", "2.1-5b", "2.1-5c", "2.1-5d",
    "2.1-6a", "2.1-6b", "2.1-6c",
    "2.1-7a",
    "2.1-8a", "2.1-8b",
    "2.1-9a", "2.1-9b",
]


def _load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


# ------------------------------------------------------------- examples ----

def test_examples_regenerate_byte_for_byte(tmp_path):
    """The mint tool is the only author of these files."""
    before = {p.name: p.read_bytes() for p in sorted(EXAMPLES.glob("*.json"))}
    subprocess.run([sys.executable,
                    str(REPO / "tools" / "mint_contract_examples.py")],
                   check=True, capture_output=True)
    after = {p.name: p.read_bytes() for p in sorted(EXAMPLES.glob("*.json"))}
    assert set(before) == set(after)
    drifted = [name for name in before if before[name] != after[name]]
    assert not drifted, (f"committed examples differ from a fresh mint: "
                         f"{drifted}. Run tools/mint_contract_examples.py.")


@pytest.mark.parametrize("example,schema", [
    ("RunManifest.v2.example.json", "RunManifest.v2.schema.json"),
    ("ContHarnessInput.example.json", "ContHarnessInput.schema.json"),
    ("ContHarnessOutput.example.json", "ContHarnessOutput.schema.json"),
])
def test_examples_conform_to_their_schema(example, schema):
    assert validate(_load(EXAMPLES / example), str(SCHEMAS / schema)) == []


def test_harness_output_carries_no_threshold():
    """No threshold and no acceptance band reaches a v0.1 output. recovery_time
    and half_life are null with a reason attached, and the schema pins that
    with a const so one cannot be set by accident before Week 3."""
    output = _load(EXAMPLES / "ContHarnessOutput.example.json")["outputs"]
    shock = output["shock_response"]
    assert shock["recovery_time"] is None
    assert shock["half_life"] is None
    assert shock["recovery_time_note"] and shock["half_life_note"]
    schema = _load(SCHEMAS / "ContHarnessOutput.schema.json")
    response = schema["$defs"]["ShockResponse"]["properties"]
    assert response["recovery_time"]["const"] is None
    assert response["half_life"]["const"] is None


def test_every_estimate_reports_a_standard_error():
    """The uncertainty convention, enforced rather than described: an estimate
    that exists states what its +/- is."""
    output = _load(EXAMPLES / "ContHarnessOutput.example.json")["outputs"]
    for window in output["ofi_regression_by_window"]:
        for key, fit in window.items():
            if not isinstance(fit, dict):
                continue
            assert "n" in fit and "ddof" in fit, (window["window_index"], key)
            if fit.get("beta") is not None:
                assert fit["standard_error"] is not None
                assert "ddof" in fit["uncertainty"]


def test_primary_specification_has_an_intercept():
    """Ruling of 2026-08-20: primary = with intercept, to stay comparable with
    the estimating equation of Cont, Kukanov and Stoikov (2014); the
    no-intercept fit is kept beside it as the proportionality diagnostic, not
    instead of it."""
    output = _load(EXAMPLES / "ContHarnessOutput.example.json")["outputs"]
    windows = output["ofi_regression_by_window"]
    assert windows
    for window in windows:
        primary = window["primary_non_price_changing"]
        assert "alpha" in primary
        assert primary["ddof"] == 2
        secondary = window["secondary_non_price_changing_no_intercept"]
        assert secondary["ddof"] == 1


# ------------------------------------------------------ resolution map ----

def _pointer_exists(schema: dict, pointer: str) -> bool:
    """Walk a RunManifest-v2 JSON Pointer through the schema's structure."""
    node = schema
    for raw in [p for p in pointer.split("/") if p]:
        segment = re.sub(r"\[.*?\]$", "", raw)
        node = _resolve_ref(schema, node)
        if segment == "*":
            node = node.get("items") or node.get("additionalProperties")
            if not isinstance(node, dict):
                return False
            continue
        properties = _resolve_ref(schema, node).get("properties", {})
        if segment not in properties:
            extra = node.get("additionalProperties")
            if isinstance(extra, dict):
                node = extra
                continue
            return False
        node = properties[segment]
    return True


def _resolve_ref(root: dict, node: dict) -> dict:
    seen = 0
    while isinstance(node, dict) and "$ref" in node and seen < 8:
        target: dict = root
        for part in node["$ref"].lstrip("#/").split("/"):
            target = target[part]
        node = target
        seen += 1
    return node if isinstance(node, dict) else {}


def test_resolution_map_covers_exactly_the_calendar_items():
    conformance = _load(CONTRACT / "conformance_map.v1.json")
    refs = [item["item_ref"] for item in conformance["items"]]
    assert refs == EXPECTED_ITEM_REFS
    assert len(set(refs)) == len(refs)


def test_every_mapped_item_resolves_to_a_field_that_exists():
    """A resolution table whose pointers do not resolve resolves nothing."""
    conformance = _load(CONTRACT / "conformance_map.v1.json")
    schema = _load(SCHEMAS / "RunManifest.v2.schema.json")
    unresolved = [item["item_ref"] for item in conformance["items"]
                  if item["field_pointer"]
                  and not _pointer_exists(schema, item["field_pointer"])]
    assert not unresolved, unresolved


def test_every_calendar_item_is_a_fail_item():
    """Ruling of 2026-08-20: the contract profile's FAIL list is every 2.1
    item. There are no WARN items in this profile."""
    conformance = _load(CONTRACT / "conformance_map.v1.json")
    assert {item["profile_status"] for item in conformance["items"]} == {"FAIL"}


def test_manifest_example_declares_the_map_it_was_checked_against():
    manifest = _load(EXAMPLES / "RunManifest.v2.example.json")
    conformance = _load(CONTRACT / "conformance_map.v1.json")
    declared = manifest["conformance_profile_id"]
    assert declared["profile_id"] == conformance["profile"]["profile_id"]
    assert declared["map_ref"] == "docs/contract/conformance_map.v1.json"


# -------------------------------------------------------- export guard ----

def test_export_refuses_to_overwrite_normative_contract_schemas():
    """The normative artefacts are the hand-authored files under schemas/.
    `sieve schemas export` writes the pydantic side; if it could write over
    them, the normative text would be silently replaced by the implementation.
    Checked by reading the source, so this test needs no numerical stack."""
    source = (REPO / "src" / "sieve" / "cli" / "app.py").read_text()
    assert "CONTRACT_SCHEMA_FILES" in source
    for name in CONTRACT_SCHEMA_FILES:
        assert name in source, name
    assert "refuses to overwrite" in source


def test_the_guard_list_matches_what_is_actually_hand_authored():
    """A hand-authored schema missing from the guard list is unprotected."""
    hand_authored = {p.name for p in SCHEMAS.glob("*.schema.json")
                     if '"$schema"' in p.read_text()[:200]}
    assert hand_authored == CONTRACT_SCHEMA_FILES, hand_authored
